import type { CompanyView, NormalizedCompany, SearchMeta, SearchSpec, SearchSource } from '@shared/types'
import { parseQuery } from './parseQuery'
import { DemoSearchProvider } from './demoProvider'
import { persistCompanyMatches } from '../data/companyRepo'
import { demoFallbackEnabled, enabledSearchProviders, providerApiKey, providerMeta, cacheApifyActor } from '../providers/registry'
import { apolloSearchCompanies } from '../providers/apollo'
import { apifySearchCompanies, apifySearchActors } from '../providers/apify'
import { aiSuggestCompanies } from './aiSuggest'
import { isAiConfigured } from '../ai/router'

export interface SearchOutcome {
  spec: SearchSpec
  companies: CompanyView[]
  meta: SearchMeta
}

function dedupe(matches: NormalizedCompany[]): NormalizedCompany[] {
  const seen = new Set<string>()
  const out: NormalizedCompany[] = []
  for (const m of matches) {
    const key = ((m.domain ?? m.name) || '').toLowerCase().trim()
    if (!key || seen.has(key)) continue
    seen.add(key)
    out.push(m)
  }
  return out
}

/**
 * Spec → provider(s) → normalise → dedupe → SQLite → UI. Shared by natural
 * language search and saved-search re-runs.
 */
export async function searchFromSpec(spec: SearchSpec, opts?: { skipHistory?: boolean }): Promise<SearchOutcome> {
  const live = enabledSearchProviders()

  const raw: NormalizedCompany[] = []
  const sources: SearchSource[] = []
  const notes: string[] = []

  for (const provider of live) {
    const apiKey = providerApiKey(provider.id)
    if (!apiKey) continue
    try {
      let found: NormalizedCompany[] = []
      if (provider.id === 'apify') {
        const terms = [spec.keywords.join(' '), spec.industries.join(' '), spec.locations.join(' ')].filter(Boolean).join(' ')
        // Try free/lower-tier actors first, then the next candidate if a run
        // fails or returns nothing.
        const candidates = await apifySearchActors(apiKey, terms)
        let lastErr: Error | null = null
        for (const c of candidates.slice(0, 4)) {
          try {
            const result = await apifySearchCompanies(spec, { token: apiKey, actorSearch: c.actorId, actorEnrich: '' })
            if (result.length > 0) {
              cacheApifyActor('search', c.actorId)
              found = result
              break
            }
          } catch (err) {
            lastErr = err instanceof Error ? err : new Error(String(err))
          }
        }
        if (found.length === 0 && lastErr) throw lastErr
        if (found.length === 0 && candidates.length === 0) throw new Error('Could not auto-find an Apify actor for this task.')
      } else {
        found = await apolloSearchCompanies(spec, apiKey)
      }
      if (found.length > 0) {
        raw.push(...found)
        sources.push({ id: provider.id, name: providerMeta(provider.id)?.name ?? provider.id })
      }
    } catch (err) {
      notes.push(`${providerMeta(provider.id)?.name ?? provider.id}: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  let usedDemo = false
  if (raw.length === 0) {
    const noLive = live.length === 0

    // Fall back to AI discovery whenever no live provider returned results —
    // whether none is configured, or a configured one is unavailable.
    if (isAiConfigured()) {
      try {
        const suggested = await aiSuggestCompanies(spec)
        if (suggested.length > 0) {
          raw.push(...suggested)
          sources.push({ id: 'ai', name: 'AI suggestions' })
          notes.push(
            noLive
              ? 'No data-provider key configured — these leads were generated by your AI gateway and are UNVERIFIED. Verify before outreach.'
              : 'Data provider(s) returned nothing or were unavailable — these leads were generated by your AI gateway and are UNVERIFIED. Verify before outreach.'
          )
        } else {
          notes.push('AI suggestions returned nothing.')
        }
      } catch (err) {
        notes.push(`AI suggestions failed (${err instanceof Error ? err.message : String(err)}).`)
      }
    }

    if (raw.length === 0) {
      if (noLive && !isAiConfigured()) {
        notes.push('No data provider and no AI gateway configured — showing the demo dataset.')
      }
      const canUseDemo = noLive || demoFallbackEnabled()
      if (canUseDemo) {
        raw.push(...new DemoSearchProvider().searchCompanies(spec))
        usedDemo = true
        sources.push({ id: 'demo', name: 'Demo dataset', demo: true })
      } else {
        notes.push('Your enabled live providers returned no results. Enable “demo fallback” in Settings to also see demo data.')
      }
    }
  }

  const matches = dedupe(raw)
  const companies = await persistCompanyMatches('', spec, matches, { skipHistory: opts?.skipHistory ?? false })
  const meta: SearchMeta = { providers: sources, usedDemo, notes }
  return { spec, companies, meta }
}

/**
 * Natural language → spec → provider(s). Uses every enabled search provider
 * that has a key; falls back to the built-in demo dataset otherwise.
 */
export async function runSearch(query: string): Promise<SearchOutcome> {
  const spec = await parseQuery(query)
  return searchFromSpec(spec)
}
